use_frameworks!

platform :ios, '9.0'

target 'MKNBHplugApp_Example' do
  pod 'MKNBHplugApp', :path => '../'

  target 'MKNBHplugApp_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
